services:
  nextapp:
    container_name: nextapp
    build:
      context: .
      dockerfile: ./docker/dev/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - blob_storage:/app/blob_storage
    environment:
      NODE_ENV: "development"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    container_name: postgres
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - .env.dev

volumes:
  postgres:
  blob_storage:
